### PR TITLE
Update SDK buildtools

### PR DESCRIPTION
**Pull request by xfumihiro**

### CODE REVIEW

**Comment by pedrovgs** [comment]
Hey @xfumihiro thanks for your PR. Can you review why your branch is failing on Travis-CI?

**Comment by xfumihiro** [comment]
I forgot to update the travis.yml file. Just fixed it.

**Comment by pedrovgs** [comment]
Thanks! I'm going to merge this PR right now!

**Comment by xfumihiro** [comment]
:+1:

**Pull request merged**
